### ISSUE TITLE
Benchmarks fail when using multithreading

### ISSUE THREAD

**Issue by lwasmuth** [Spectral-Analysis-UPB/PyZEAL#13]
asv fails to run benchmarks for both the Newton-Grid and Simple Argument Rootfinders. An exception is raised with `ModuleNotFoundError: No module named 'benchmarks'` by multiple worker processes spawned asv. However, the traceback doesn't have any useful information, as it only shows parts of execution inside the multiprocessing package. The issue doesn't occur for the Newton-Grid-Rootfinder if finder_interface.py calls runRootJobs sequentially instead of using starmap.

The same error appears when using the multiprocessing going back to commit [c7287ff](https://github.com/Spectral-Analysis-UPB/PyZEAL/commit/c7287ff9af2c0fd5ca5c6846b2adb6be92e10b27), but as earlier versions only used multiprocessing when `numSamplePoints` was large enough, the error did not appear.

**Comment by lwasmuth** [comment]
A minimal example would be
```python
from multiprocessing import Pool

class Minimal:
    def __init__(self, f):
        self.f = f
    
    def do(self):
        with Pool() as p:
            p.starmap(self.func, ["a"])
    
    def func(self, s):
        pass
```
with benchmark script
```python
from pyzeal.minimal import Minimal

def f(x):
    pass

class MiniSuite:
    def TimeMini(self):
        m = Minimal(f)
        m.do()
```
The issue stops if either the line ```self.f=f``` or ```with Pool() as p: p.starmap(self.func, ["a"])``` in `Minimal` is removed. The same thing also occurs when using `p.map`.

**Comment by PhilippSchuette** [comment]
See issue #27.
