### ISSUE TITLE
Create introduction for the documentation

### ISSUE THREAD

**Issue by PhilippSchuette** [Spectral-Analysis-UPB/PyZEAL#3]
Create a short introductory section for the HTML documentation (general purpose of this project, why this project provides something new, approach taken with the project, ...).

**Comment by lwasmuth** [comment]
Add short introduction and theoretical background page
https://github.com/Spectral-Analysis-UPB/PyZEAL/commit/dc16836a4297282841e8781cca45cab63ee4c61e
